import { QuestionType } from "@prisma/client";
import prisma from "../prisma";

export async function seedRound3(competitionId: string): Promise<void> {
  const round = await prisma.round.create({
    data: {
      competitionId,
      orderIndex: 3,
      type: "STREAK",
      title: "Рунд 3: Вярно или невярно",
    },
  });

  await prisma.question.createMany({
    data: [
      {
        roundId: round.id,
        index: 0,
        realIndex: 0,
        questionText: "Според Библията стените на Ерусалим са построени от ЛЕГО тухли.",
        type: "TRUE_FALSE" as QuestionType,
        points: 0,
        timeLimitSeconds: 10,
        content: { isTrue: false },
      },
      {
        roundId: round.id,
        index: 1,
        realIndex: 1,
        questionText: "Ной взе в ковчега си динозаври.",
        type: "TRUE_FALSE" as QuestionType,
        points: 1,
        timeLimitSeconds: 10,
        content: { isTrue: false },
      },
      {
        roundId: round.id,
        index: 2,
        realIndex: 2,
        questionText: "Мойсей раздели Червено море с помощта на Бога.",
        type: "TRUE_FALSE" as QuestionType,
        points: 1,
        timeLimitSeconds: 10,
        content: { isTrue: true },
      },

      {
        roundId: round.id,
        index: 0,
        realIndex: 3,
        questionText: "Кое е вярното твърдение за маймуните?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 0,
        content: {
          options: ["Те ядат само банани", "Те могат да ядат различни плодове, ядки, растения и дори дребни животни"],
          correctIndices: [1],
        },
      },
      {
        roundId: round.id,
        index: 3,
        realIndex: 4,
        questionText: "Колко дни Бог създаде света?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Шест дни", "Седем дни"],
          correctIndices: [1],
        },
      },
      {
        roundId: round.id,
        index: 4,
        realIndex: 5,
        questionText: "Коя планина Мойсей получи десетте заповеди?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Синай", "Хорив"],
          correctIndices: [0],
        },
      },
      {
        roundId: round.id,
        index: 5,
        realIndex: 6,
        questionText: "Колко дни Бог създаде света?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Шест дни", "Седем дни"],
          correctIndices: [1],
        },
      },
      {
        roundId: round.id,
        index: 6,
        realIndex: 7,
        questionText: "Коя планина Мойсей получи десетте заповеди?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Синай", "Хорив"],
          correctIndices: [0],
        },
      },
      {
        roundId: round.id,
        index: 7,
        realIndex: 8,
        questionText: "Колко дни Бог създаде света?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Шест дни", "Седем дни"],
          correctIndices: [1],
        },
      },
      {
        roundId: round.id,
        index: 8,
        realIndex: 9,
        questionText: "Коя планина Мойсей получи десетте заповеди?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Синай", "Хорив"],
          correctIndices: [0],
        },
      },
      {
        roundId: round.id,
        index: 9,
        realIndex: 10,
        questionText: "Колко дни Бог създаде света?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Шест дни", "Седем дни"],
          correctIndices: [1],
        },
      },
      {
        roundId: round.id,
        index: 10,
        realIndex: 11,
        questionText: "Коя планина Мойсей получи десетте заповеди?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Синай", "Хорив"],
          correctIndices: [0],
        },
      },
      {
        roundId: round.id,
        index: 11,
        realIndex: 12,
        questionText: "Колко дни Бог създаде света?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Шест дни", "Седем дни"],
          correctIndices: [1],
        },
      },
      {
        roundId: round.id,
        index: 12,
        realIndex: 13,
        questionText: "Коя планина Мойсей получи десетте заповеди?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Синай", "Хорив"],
          correctIndices: [0],
        },
      },
      {
        roundId: round.id,
        index: 13,
        realIndex: 14,
        questionText: "Колко дни Бог създаде света?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Шест дни", "Седем дни"],
          correctIndices: [1],
        },
      },
      {
        roundId: round.id,
        index: 14,
        realIndex: 15,
        questionText: "Коя планина Мойсей получи десетте заповеди?",
        type: "MULTIPLE_CHOICE",
        timeLimitSeconds: 15,
        points: 1,
        content: {
          options: ["Синай", "Хорив"],
          correctIndices: [0],
        },
      },

      {
        roundId: round.id,
        index: 0,
        realIndex: 16,
        questionText: "Поправи грешката в изречението",
        type: "CORRECT_THE_ERROR" as QuestionType,
        points: 0,
        content: {
          text: "Старшият конструктор учи Младшия конструктор как се строи с нова кирка.",
          words: [
            { wordIndex: 8, text: "кирка", alternatives: ["тухли", "каска"] },
          ],
          errorWordIndex: 8,
          correctReplacement: "тухли",
        },
      },
      {
        roundId: round.id,
        index: 15,
        realIndex: 17,
        questionText: "Поправи грешката в изречението",
        type: "CORRECT_THE_ERROR" as QuestionType,
        points: 2,
        content: {
          text: "Мойсей раздели Червеното море с помощта на Илия",
          words: [
            { wordIndex: 0, text: "Мойсей", alternatives: ["Исус", "Илия"] },
            { wordIndex: 2, text: "Червеното", alternatives: ["Черното", "Галилейското"] },
            { wordIndex: 7, text: "Илия", alternatives: ["Бог", "Ангел"] },
          ],
          errorWordIndex: 7,
          correctReplacement: "Бог",
        },
      },
      {
        roundId: round.id,
        index: 16,
        realIndex: 18,
        questionText: "Поправи грешката в изречението",
        type: "CORRECT_THE_ERROR" as QuestionType,
        points: 2,
        content: {
          text: "Давид уби Голиат с помощта на своята тояга",
          words: [
            { wordIndex: 0, text: "Давид", alternatives: ["Саул", "Йонатан"] },
            { wordIndex: 2, text: "Голиат", alternatives: ["Филистимец", "Саул"] },
            { wordIndex: 7, text: "тояга", alternatives: ["лрашка", "арфа"] },
          ],
          errorWordIndex: 7,
          correctReplacement: "прашка",
        },
      },
    ],
  });
}
